version: "2.2"
services:
    elasticsearch:
        image: elasticsearch:7.9.3
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.9.3
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.9.3
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - .\logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    registry:
        image: descartesresearch/teastore-registry
        expose:
          - "8080"
    registry:
        image: descartesresearch/teastore-registry
        expose:
          - "8080"
    db:
        image: descartesresearch/teastore-db
        expose:
          - "3306"
        ports:
          - "3306:3306"
    persistence:
        image: descartesresearch/teastore-persistence
        expose:
          - "8080"
        environment:
          HOST_NAME: "persistence"
          REGISTRY_HOST: "registry"
          DB_HOST: "db"
          DB_PORT: "3306"
          LOG_TO_FILE: "true"
    auth:
        image: descartesresearch/teastore-auth
        expose:
          - "8080"
        environment:
          HOST_NAME: "auth"
          REGISTRY_HOST: "registry"
          LOG_TO_FILE: "true"
    image:
        image: descartesresearch/teastore-image
        expose:
          - "8080"
        environment:
          HOST_NAME: "image"
          REGISTRY_HOST: "registry"
          LOG_TO_FILE: "true"
    recommender:
        image: descartesresearch/teastore-recommender
        expose:
          - "8080"
        environment:
          HOST_NAME: "recommender"
          REGISTRY_HOST: "registry"
          LOG_TO_FILE: "true"
    webui:
        image: descartesresearch/teastore-webui
        environment:
          HOST_NAME: "webui"
          REGISTRY_HOST: "registry"
          LOG_TO_FILE: "false"
        ports:
          - "8080:8080"
        volumes:
          - .\webui:/home/logs
networks:
    elknetwork:
        driver: bridge